---
title: "Condensed Teeth Pilot Analysis"
output: html_document
---

<style type="text/css">
h1 {
  font-size: 36px;
  margin-top: 60px;
  margin-bottom: 30px;
}

h2 {
  font-size: 28px;

}

h3 {
  font-size: 24px;
  padding-top: 30px;
  margin-bottom: 0px;
  text-align: left !important;
}

h4 {
  font-size: 16px;
}

h5 {
 font-size: 14px;
}

p {
  font-size: 12px;
  text-align: left;
  line-height: 1;
}

h1, h2, h3, h4, h5, h6 {
  text-align: center;
  line-height: 1;
}

.p-text-align-right {
  text-align: right !important;
}

</style>

```{r, include=FALSE,warning=FALSE}
# clean workspace
rm(list=ls())

# load required packages
packages <- c("ggplot2", "ggpubr")
lapply(packages, library, character.only = TRUE)

#ggplot titles should be in center
theme_set(theme_bw() + theme( plot.title = element_text(size=18, lineheight=1, margin=margin(b=15, t=30), hjust = 0.5),
         axis.title.x = element_text(size=14, lineheight=1, margin=margin(t=15)),
         axis.title.y = element_text(size=14, lineheight=1, margin=margin(r=15))))

##################
## read in data ##
##################
data<-read.csv("/Users/appollo_liu/Documents/workspace/Tooth_Brushing/data/parent_q_clean_n19.csv", header=TRUE)

# makes each "key" in the data object it's own variable
# Example: data$record_id is now record_id
attach(data)

# list of interesting data columns
# age_firstword_recode_mos, parent1_edu, parent2_edu, income_median, num_siblings, child_birth_weight, age_walking_recode_mos
```

### Random but beautiful plots

```{r,warning=FALSE,fig.width=10, fig.height=8,echo = FALSE}

# add the two arrays of parent education to find total years of educaiton
combined_parent_education<-mapply(function(x1, y1) x1[[1]]+y1[[1]], parent1_edu, parent2_edu)

# plot Income Median vs. Combined Parent Education
income_vs_education <- ggplot(data=data, mapping=aes(x=combined_parent_education, y=income_median))
income_vs_education + 
  geom_point(shape=1) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE) + 
  labs(title="Median Income vs. Combined Parent Education", x="Combined Parent Education (years)",y="Median Income ($)") + 
  stat_cor(method = "pearson",  size = 6)

# plot Child Birth Weight vs. Median Income
weight_vs_income <- ggplot(data=data, mapping=aes(x=income_median, y=child_birth_weight))
weight_vs_income + 
  geom_point(shape=1) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE) + 
  labs(title="Child Birth Weight vs. Median Income", x="Median Income ($)",y="Child Birth Weight (lbs)") + 
  stat_cor(method = "pearson",  size = 6) +
  ylim(0, 20)

# plot First Word Age vs. Combined Parent Education
child_speech_vs_parent_education <- ggplot(data=data, mapping=aes(x=combined_parent_education, y=age_firstword_recode_mos))
child_speech_vs_parent_education + 
  geom_point(shape=1) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE) + 
  labs(title="First Word Age vs. Combined Parent Education", x="Combined Parent Education (years)",y="First Word Age (months)") + 
  stat_cor(method = "pearson",  size = 6)
```

<p class="p-text-align-right">
  Note that all children were monolingual.
</p>

```{r,warning=FALSE,fig.width=10, fig.height=8,echo=FALSE}

# plot Number of Siblings vs. Median Income
siblings_vs_income <- ggplot(data=data, mapping=aes(x=income_median, y=num_siblings))
siblings_vs_income + 
  geom_point(shape=1) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE) + 
  labs(title="Number of Siblings vs. Median Income", x="Median Income ($)",y="Number of Siblings") +
  stat_cor(method = "pearson",  size = 6)
```